// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module LeNet_LeNet_Pipeline_VITIS_LOOP_15_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        param_arr_address0,
        param_arr_ce0,
        param_arr_q0,
        kernel_bias_layer1_V_2_03_out,
        kernel_bias_layer1_V_2_03_out_ap_vld,
        kernel_bias_layer1_V_1_02_out,
        kernel_bias_layer1_V_1_02_out_ap_vld,
        kernel_bias_layer1_V_0_01_out,
        kernel_bias_layer1_V_0_01_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] param_arr_address0;
output   param_arr_ce0;
input  [15:0] param_arr_q0;
output  [15:0] kernel_bias_layer1_V_2_03_out;
output   kernel_bias_layer1_V_2_03_out_ap_vld;
output  [15:0] kernel_bias_layer1_V_1_02_out;
output   kernel_bias_layer1_V_1_02_out_ap_vld;
output  [15:0] kernel_bias_layer1_V_0_01_out;
output   kernel_bias_layer1_V_0_01_out_ap_vld;

reg ap_idle;
reg param_arr_ce0;
reg kernel_bias_layer1_V_2_03_out_ap_vld;
reg kernel_bias_layer1_V_1_02_out_ap_vld;
reg kernel_bias_layer1_V_0_01_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln15_fu_113_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [1:0] k_2_reg_208;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] index_cast_fu_128_p1;
wire    ap_block_pp0_stage0;
reg   [6:0] index_fu_46;
wire   [6:0] add_ln16_fu_133_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_index_load;
reg   [1:0] k_fu_50;
wire   [1:0] add_ln15_fu_119_p2;
reg   [1:0] ap_sig_allocacmp_k_2;
reg   [15:0] kernel_bias_layer1_V_1_fu_54;
reg   [15:0] kernel_bias_layer1_V_1_1_fu_58;
reg   [15:0] kernel_bias_layer1_V_1_2_fu_62;
wire    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

LeNet_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15_fu_113_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            index_fu_46 <= add_ln16_fu_133_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            index_fu_46 <= 7'd75;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln15_fu_113_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_50 <= add_ln15_fu_119_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_50 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_2_reg_208 <= ap_sig_allocacmp_k_2;
    end
end

always @ (posedge ap_clk) begin
    if (((k_2_reg_208 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_layer1_V_1_1_fu_58 <= param_arr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(k_2_reg_208 == 2'd0) & ~(k_2_reg_208 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_layer1_V_1_2_fu_62 <= param_arr_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((k_2_reg_208 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_layer1_V_1_fu_54 <= param_arr_q0;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_113_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_index_load = 7'd75;
    end else begin
        ap_sig_allocacmp_index_load = index_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_2 = 2'd0;
    end else begin
        ap_sig_allocacmp_k_2 = k_fu_50;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_113_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_layer1_V_0_01_out_ap_vld = 1'b1;
    end else begin
        kernel_bias_layer1_V_0_01_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_113_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_layer1_V_1_02_out_ap_vld = 1'b1;
    end else begin
        kernel_bias_layer1_V_1_02_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_113_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_layer1_V_2_03_out_ap_vld = 1'b1;
    end else begin
        kernel_bias_layer1_V_2_03_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        param_arr_ce0 = 1'b1;
    end else begin
        param_arr_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_fu_119_p2 = (ap_sig_allocacmp_k_2 + 2'd1);

assign add_ln16_fu_133_p2 = (ap_sig_allocacmp_index_load + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln15_fu_113_p2 = ((ap_sig_allocacmp_k_2 == 2'd3) ? 1'b1 : 1'b0);

assign index_cast_fu_128_p1 = ap_sig_allocacmp_index_load;

assign kernel_bias_layer1_V_0_01_out = kernel_bias_layer1_V_1_fu_54;

assign kernel_bias_layer1_V_1_02_out = kernel_bias_layer1_V_1_1_fu_58;

assign kernel_bias_layer1_V_2_03_out = kernel_bias_layer1_V_1_2_fu_62;

assign param_arr_address0 = index_cast_fu_128_p1;

endmodule //LeNet_LeNet_Pipeline_VITIS_LOOP_15_4
