// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module LeNet_LeNet_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_VITIS_LOOP_9_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer2_output_V_address0,
        layer2_output_V_ce0,
        layer2_output_V_we0,
        layer2_output_V_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] layer2_output_V_address0;
output   layer2_output_V_ce0;
output   layer2_output_V_we0;
output  [15:0] layer2_output_V_d0;

reg ap_idle;
reg layer2_output_V_ce0;
reg layer2_output_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln7_fu_122_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln10_3_fu_304_p1;
reg   [1:0] k_out_fu_60;
wire   [1:0] add_ln9_1_fu_309_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_k_out_load;
reg   [3:0] c_fu_64;
wire   [3:0] select_ln8_fu_216_p3;
reg   [3:0] ap_sig_allocacmp_c_load;
reg   [5:0] indvar_flatten204_fu_68;
wire   [5:0] select_ln8_4_fu_321_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten204_load;
reg   [3:0] r_fu_72;
wire   [3:0] select_ln7_1_fu_166_p3;
reg   [3:0] ap_sig_allocacmp_r_load;
reg   [8:0] indvar_flatten218_fu_76;
wire   [8:0] add_ln7_2_fu_128_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten218_load;
wire   [0:0] icmp_ln8_fu_152_p2;
wire   [3:0] add_ln7_fu_146_p2;
wire   [0:0] icmp_ln9_fu_184_p2;
wire   [0:0] xor_ln7_fu_178_p2;
wire   [3:0] select_ln7_fu_158_p3;
wire   [0:0] and_ln7_fu_190_p2;
wire   [0:0] or_ln8_fu_202_p2;
wire   [3:0] add_ln8_1_fu_196_p2;
wire   [1:0] select_ln8_3_fu_208_p3;
wire   [5:0] tmp_s_fu_228_p3;
wire   [3:0] tmp_9_fu_240_p3;
wire   [6:0] zext_ln10_fu_236_p1;
wire   [6:0] zext_ln10_2_fu_248_p1;
wire   [6:0] sub_ln10_fu_252_p2;
wire  signed [7:0] sext_ln10_fu_258_p1;
wire   [7:0] zext_ln8_fu_174_p1;
wire   [7:0] add_ln10_fu_262_p2;
wire   [4:0] trunc_ln10_fu_268_p1;
wire   [6:0] trunc_ln10_1_fu_280_p1;
wire   [8:0] p_shl13_cast_fu_272_p3;
wire   [8:0] p_shl15_cast_fu_284_p3;
wire   [8:0] sub_ln10_1_fu_292_p2;
wire   [8:0] select_ln8_4_cast_fu_224_p1;
wire   [8:0] add_ln10_2_fu_298_p2;
wire   [5:0] add_ln8_fu_315_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

LeNet_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln7_fu_122_p2 == 1'd0)) begin
            c_fu_64 <= select_ln8_fu_216_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_64 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln7_fu_122_p2 == 1'd0)) begin
            indvar_flatten204_fu_68 <= select_ln8_4_fu_321_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten204_fu_68 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln7_fu_122_p2 == 1'd0)) begin
            indvar_flatten218_fu_76 <= add_ln7_2_fu_128_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten218_fu_76 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln7_fu_122_p2 == 1'd0)) begin
            k_out_fu_60 <= add_ln9_1_fu_309_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_out_fu_60 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln7_fu_122_p2 == 1'd0)) begin
            r_fu_72 <= select_ln7_1_fu_166_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_72 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_122_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_c_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_64;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten204_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten204_load = indvar_flatten204_fu_68;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten218_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten218_load = indvar_flatten218_fu_76;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_k_out_load = 2'd0;
    end else begin
        ap_sig_allocacmp_k_out_load = k_out_fu_60;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_r_load = 4'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_72;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_output_V_ce0 = 1'b1;
    end else begin
        layer2_output_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_122_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer2_output_V_we0 = 1'b1;
    end else begin
        layer2_output_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_2_fu_298_p2 = (sub_ln10_1_fu_292_p2 + select_ln8_4_cast_fu_224_p1);

assign add_ln10_fu_262_p2 = ($signed(sext_ln10_fu_258_p1) + $signed(zext_ln8_fu_174_p1));

assign add_ln7_2_fu_128_p2 = (ap_sig_allocacmp_indvar_flatten218_load + 9'd1);

assign add_ln7_fu_146_p2 = (ap_sig_allocacmp_r_load + 4'd1);

assign add_ln8_1_fu_196_p2 = (select_ln7_fu_158_p3 + 4'd1);

assign add_ln8_fu_315_p2 = (ap_sig_allocacmp_indvar_flatten204_load + 6'd1);

assign add_ln9_1_fu_309_p2 = (select_ln8_3_fu_208_p3 + 2'd1);

assign and_ln7_fu_190_p2 = (xor_ln7_fu_178_p2 & icmp_ln9_fu_184_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln7_fu_122_p2 = ((ap_sig_allocacmp_indvar_flatten218_load == 9'd432) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_152_p2 = ((ap_sig_allocacmp_indvar_flatten204_load == 6'd36) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_184_p2 = ((ap_sig_allocacmp_k_out_load == 2'd3) ? 1'b1 : 1'b0);

assign layer2_output_V_address0 = zext_ln10_3_fu_304_p1;

assign layer2_output_V_d0 = 16'd0;

assign or_ln8_fu_202_p2 = (icmp_ln8_fu_152_p2 | and_ln7_fu_190_p2);

assign p_shl13_cast_fu_272_p3 = {{trunc_ln10_fu_268_p1}, {4'd0}};

assign p_shl15_cast_fu_284_p3 = {{trunc_ln10_1_fu_280_p1}, {2'd0}};

assign select_ln7_1_fu_166_p3 = ((icmp_ln8_fu_152_p2[0:0] == 1'b1) ? add_ln7_fu_146_p2 : ap_sig_allocacmp_r_load);

assign select_ln7_fu_158_p3 = ((icmp_ln8_fu_152_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_c_load);

assign select_ln8_3_fu_208_p3 = ((or_ln8_fu_202_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_k_out_load);

assign select_ln8_4_cast_fu_224_p1 = select_ln8_fu_216_p3;

assign select_ln8_4_fu_321_p3 = ((icmp_ln8_fu_152_p2[0:0] == 1'b1) ? 6'd1 : add_ln8_fu_315_p2);

assign select_ln8_fu_216_p3 = ((and_ln7_fu_190_p2[0:0] == 1'b1) ? add_ln8_1_fu_196_p2 : select_ln7_fu_158_p3);

assign sext_ln10_fu_258_p1 = $signed(sub_ln10_fu_252_p2);

assign sub_ln10_1_fu_292_p2 = (p_shl13_cast_fu_272_p3 - p_shl15_cast_fu_284_p3);

assign sub_ln10_fu_252_p2 = (zext_ln10_fu_236_p1 - zext_ln10_2_fu_248_p1);

assign tmp_9_fu_240_p3 = {{select_ln8_3_fu_208_p3}, {2'd0}};

assign tmp_s_fu_228_p3 = {{select_ln8_3_fu_208_p3}, {4'd0}};

assign trunc_ln10_1_fu_280_p1 = add_ln10_fu_262_p2[6:0];

assign trunc_ln10_fu_268_p1 = add_ln10_fu_262_p2[4:0];

assign xor_ln7_fu_178_p2 = (icmp_ln8_fu_152_p2 ^ 1'd1);

assign zext_ln10_2_fu_248_p1 = tmp_9_fu_240_p3;

assign zext_ln10_3_fu_304_p1 = add_ln10_2_fu_298_p2;

assign zext_ln10_fu_236_p1 = tmp_s_fu_228_p3;

assign zext_ln8_fu_174_p1 = select_ln7_1_fu_166_p3;

endmodule //LeNet_LeNet_Pipeline_VITIS_LOOP_7_1_VITIS_LOOP_8_2_VITIS_LOOP_9_3
